tap "bazelbuild/tap", pin: true
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
cask "osxfuse"
brew "ocaml"
brew "etcd"
brew "fpp"
brew "git-extras"
brew "googler"
brew "httpie"
brew "hub"
brew "jq"
brew "kubernetes-cli"
brew "libxmlsec1"
brew "protobuf"
brew "mitmproxy"
brew "mysql@5.7"
brew "opam"
brew "postgresql@9.6", restart_service: true, link: true
brew "rbenv"
brew "redis@3.2", restart_service: true
brew "ruby"
brew "sshfs"
brew "tig"
brew "tree"
brew "yarn", args: ["without-node"]
brew "zsh-syntax-highlighting"
cask "cheatsheet"
cask "chromedriver"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "goland"
cask "minikube"
cask "ngrok"
cask "shiftit"
cask "slack"
